### ISSUE TITLE
Socket connection error

### ISSUE THREAD

**Issue by ankaerith** [mcclurec/homebridge-volumio-speakers#13]
The plugin started throwing these errors.  I've tried changing around the configuration, restarting homebridge and rebooting.  No luck.  

SPEAKER: Socket connection error: http://127.0.0.1:3000 Error: xhr poll error
    at XHR.Transport.onError (/usr/local/lib/node_modules/homebridge-volumio-speakers/node_modules/engine.io-client/lib/transport.js:68:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-volumio-speakers/node_modules/engine.io-client/lib/transports/polling-xhr.js:132:10)
    at Request.Emitter.emit (/usr/local/lib/node_modules/homebridge-volumio-speakers/node_modules/component-emitter/index.js:145:20)
    at Request.onError (/usr/local/lib/node_modules/homebridge-volumio-speakers/node_modules/engine.io-client/lib/transports/polling-xhr.js:314:8)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-volumio-speakers/node_modules/engine.io-client/lib/transports/polling-xhr.js:261:18)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  type: 'TransportError',
  description: 0
}

SPEAKER: Socket reconnection error: Error: xhr poll error
    at XHR.Transport.onError (/usr/local/lib/node_modules/homebridge-volumio-speakers/node_modules/engine.io-client/lib/transport.js:68:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-volumio-speakers/node_modules/engine.io-client/lib/transports/polling-xhr.js:132:10)
    at Request.Emitter.emit (/usr/local/lib/node_modules/homebridge-volumio-speakers/node_modules/component-emitter/index.js:145:20)
    at Request.onError (/usr/local/lib/node_modules/homebridge-volumio-speakers/node_modules/engine.io-client/lib/transports/polling-xhr.js:314:8)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-volumio-speakers/node_modules/engine.io-client/lib/transports/polling-xhr.js:261:18)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  type: 'TransportError',
  description: 0
}

**Comment by mcclurec** [comment]
Sorry for the slow reply... `127.0.0.1` is a [loopback address](https://en.wikipedia.org/wiki/Localhost#:~:text=The%20address%20127.0.0.1%20is,on%20the%20same%20port%20number.) meaning the Volumio server is incorrectly identifying it's IP address as itself. This is a bug within Volumio that I've seen. Restarting your Volumio server should fix the issue. Let me know if that doesn't fix it.

**Comment by ankaerith** [comment]
Rebooting doesn't fix it.  I've updated homebridge, node, OS packages, and rebooted multiple times.

**Comment by ankaerith** [comment]
That did it.  Thanks.
